[package]
name = "autoguard"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk = { package = "gtk4", version = "0.9" }
glib = "0.20"
rust-ini = "0.20"
dirs = "5"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"

[build-dependencies]
glib-build-tools = "0.18"
